language: cpp

before_script:

script: 
  - mkdir bin
  - cd bin
  - cmake -G "Unix Makefiles" ..
  - make
  - ls 
  - cpack -G DEB --debug -V
  - cat _CPack_Packages/Linux/DEB/PreinstallOutput.log