language: cpp

before_script:

script: 
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" ..
  - cmake --build .
  - cd ../bin
  - cpack -G DEB
  - cat _CPack_Packages/Linux/DEB/PreinstallOutput.log